# Файл исключений для функции объединения файлов
# Формат: списки директорий и расширений файлов для исключения

# Директории, которые следует исключить при объединении файлов
[directories]
exclude = [
  ".git",
  "node_modules",
  ".vscode",
  "dist",
  "build",
  "coverage",
  "tmp"
]

# Файлы, которые следует исключить при объединении файлов
[files]
exclude = [
  ".env",
  ".DS_Store",
  "combined_code_ignore.toml"
]

# Маски файлов для исключения (поддерживает * как подстановочный знак)
[patterns]
exclude = [
  "combined_code*.txt",
  "*.log",
  "*.tmp"
]

# Расширения файлов, которые следует исключить при объединении файлов
[extensions]
exclude = [
  ".exe",
  ".dll",
  ".jpg",
  ".jpeg",
  ".png",
  ".gif",
  ".mp3",
  ".mp4",
  ".zip",
  ".rar",
  ".7z",
  ".pdf",
  ".lock",
  ".bin"
]
