# Пример файла setup.toml
[folders]
sources = ["главная", "вторая"]
docs = ["отчеты", "заметки"]

[files]
"README.md" = "# Проект создан с помощью setup-module"
"settings.json" = """
{
    "editor.tabSize": 4,
    "editor.insertSpaces": true
}
"""
